name: 'Hashnode Blog'
description: 'Pulls Your Latest Blog Post From Hashnode'
author: 'Phonghaw2'

inputs:
  BLOG_URL:
    description: "Your Hashnode publication name, Ex: blog.hashnode.dev"
    required: true
  FILE:
    description: "Provide a valid file location"
    default: "README.md"
    required: false
  STYLE:
    description: "Provide which style you need"
    default: 'list'
    required: false
  LIMIT:
    description: "Number of latest post to show"
    default: "6"
    required: false

branding:
  icon: 'book-open'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/index.js'
